#wasq that returns custo name either starts with vovel or ends with vovel

select * from customers;

SELECT CONTACTFIRSTNAME FROM CUSTOMERS
WHERE
LEFT(CONTACTFIRSTNAME,1) IN ('A','E','I','O','U')
OR RIGHT(CONTACTFIRSTNAME,1) IN ('a','e','i','o','u');


SELECT CUSTOMERNAME FROM CUSTOMERS
WHERE
SUBSTRING(CUSTOMERNAME,1,1) IN ('A','E','I','O','U')
OR SUBSTRING(CUSTOMERNAME,-1,1) IN ('a','e','i','o','u');

#WASQ TO FIND THE PRODUCT WHOSE NAME CONTAINS THE CAR KEYWORD
SELECT * FROM PRODUCTS;


SELECT  PRODUCTNAME FROM PRODUCTS
WHERE INSTR(PRODUCTNAME, "CAR");

SELECT PRODUCTNAME FROM PRODUCTS
WHERE PRODUCTNAME like "%CAR%";
