######## DATE FUNCTION #################

SELECT NOW();

SELECT SYSDATE();

SELECT current_date();

SELECT current_time();

#########################################

SELECT NOW(), SLEEP(5),NOW();

SELECT SYSDATE(),SLEEP(5), SYSDATE();

###########################################

#DATEDIFF

SELECT DATEDIFF("1992-07-14","2024-07-24");

SELECT ROUND(DATEDIFF("2024-07-24","1992-07-14")/364,0);


#WASQ THAT RETURNS THE NO OF DAYS BTW REQUIRE DATE AND SHIP DATE 

SELECT * FROM ORDERS;

SELECT ORDERNUMBER,
IFNULL(DATEDIFF(REQUIREDDATE,SHIPPEDDATE),"N/A") AS DAYS 
FROM ORDERS
ORDER BY DAYS;